#' Demographics
#'
#' Participant demographics collected through an onboarding survey prior to claim assessment. This data 
#' is stored in long format with one row per participant. This data is stored in wide format with one 
#' row per participant. 
#'
#' @format A tibble with 1,027 rows and 91 column variables:
#' \describe{
#' \item{user_name}{Unique, anonymised, alphanumeric identifier for the participant.}
#' \item{Progress}{Percentage of demographics survey completed.}
#' \item{Finished}{Did participant complete demographics survey?}
#' \item{recorded_date}{Date-time survey was completed. In %Y-%m-%d %H:%M:%S or yyyy-mm-dd hh:mm:ss format.}
#' \item{ResponseId}{Unique ID for quiz data point.}
#' \item{SCORE_involvement}{Binary indicator for participant involvement in SCORE project outside of human elicited judgements.}
#' \item{english_language_ability}{Participants’ self-rated English language ability.}
#' \item{highest_education_level}{Participants’ highest level of completed education.}
#' \item{highest_degree_field_of_research}{Participants’ highest completed degree’s field of research selected from list.}
#' \item{highest_degree_field_of_research_free_text}{Participants’ highest completed degree’s field of research free text for fields not represented in list.}
#' \item{field_of_research_Business}{Binary indicator for participant’s field of research being “Business”.}
#' \item{field_of_research_Criminology}{Binary indicator for participant’s field of research being “Criminology”.}
#' \item{field_of_research_Economics}{Binary indicator for participant’s field of research being “Economics”.}
#' \item{field_of_research_Education}{Binary indicator for participant’s field of research being “Education”.}
#' \item{field_of_research_Political_Science}{Binary indicator for participant’s field of research being “Political Science”.}
#' \item{field_of_research_Psychology}{Binary indicator for participant’s field of research being “Psychology”.}
#' \item{field_of_research_Public_Administration}{Binary indicator for participant’s field of research being “Administration”.}
#' \item{field_of_research_Sociology}{Binary indicator for participant’s field of research being “Sociology”.}
#' \item{field_of_research_Metascience_Metaresearch}{Binary indicator for participant’s field of research being “Metascience or Metaresearch”.}
#' \item{field_of_research_Other}{Binary indicator for participant’s field of research being “Other”.}
#' \item{field_of_research_Prefer_Not_To_Say}{Binary indicator for participant not wishing to disclose their field of research.}
#' \item{field_of_research_Other_free_Text}{Participants’ self-reported field of research if no present in list.}
#' \item{current_position_type}{Participants’ current position type selected from list.}
#' \item{current_position_type_free_text}{Participants’ self-reported current position type if not present in list.}
#' \item{career_stage}{Participants’ self-reported career stage selected from list.}
#' \item{career_stage_free_text}{Participants’ self-reported career stage if not present in list.}
#' \item{expertise_Mathematics}{Participants’ self-reported expertise in “Mathematics” selected from list.}
#' \item{expertise_Quantitative_Modelling_and_Simulation}{Participants’ self-reported expertise in “Quantitative Modelling and Simulation” selected from list.}
#' \item{expertise_Statistics}{Participants’ self-reported expertise in “Statistics” selected from list.}
#' \item{expertise_Probability}{Participants’ self-reported expertise in “Probability” selected from list.}
#' \item{expertise_Experimental_Design}{Participants’ self-reported expertise in “Experimental Design” selected from list.}
#' \item{expertise_Risk_Analysis}{Participants’ self-reported expertise in “Risk Analysis” selected from list.}
#' \item{expertise_Forecasting}{Participants’ self-reported expertise in “Forecasting” selected from list.}
#' \item{experience_Editorial_Board}{Binary indicator for participants’ experience with “Editorial Boards”.}
#' \item{experience_Direct_Replication_Study}{Binary indicator for participants’ experience with “Direct Replication Studies”.}
#' \item{experience_Partial_or_Conceptual_Replication_Study}{Binary indicator for participants’ experience with “Partial or Conceptual Replication Studies”.}
#' \item{experience_Survey_or_Prediction_Markets}{Binary indicator for participants’ experience with “Survey or Prediction Markets”.}
#' \item{experience_Metaresearch}{Binary indicator for participants’ experience with “Metaresearch”.}
#' \item{experience_Preregistration}{Binary indicator for participants’ experience with “Preregistration”.}
#' \item{publication_count}{Participants’ number of published papers. Selected from categories in phase one, self-reported numeric in phase two.}
#' \item{publication_count_research_methods_or_statistics}{Participants’ number of published papers on research methods or statistics. Selected from categories in phase one, self-reported numeric in phase two.}
#' \item{course_count_statistics}{Participants’ number of attended courses on statistics.}
#' \item{experience_teaching_statistics_or_quantitative_methods}{Participants’ level of experience with teaching statistics or quantitative methods, selected from a list.}
#' \item{p_values_Q01}{Participants’ True/False/I don’t know response to: “Suppose that a research article reports p= .001 to support a research claim (alpha = .05). Please indicate whether the following statements are True or False: You have absolutely proven your alternative hypothesis (that is, you have proven that there is a difference between the population means)".}
#' \item{p_values_Q02}{Participants’ True/False/I don’t know response to: “Suppose that a research article reports p= .001 to support a research claim (alpha = .05). Please indicate whether the following statements are True or False: You have found the probability of the null hypothesis being true (p = .001)".}
#' \item{p_values_Q03}{Participants’ True/False/I don’t know response to: “Suppose that a research article reports p= .001 to support a research claim (alpha = .05). Please indicate whether the following statements are True or False: The null hypothesis has been shown to be false".}
#' \item{p_values_Q04}{Participants’ True/False/I don’t know response to: “Suppose that a research article reports p= .001 to support a research claim (alpha = .05). Please indicate whether the following statements are True or False: he p-value gives the probability of obtaining a significant result whenever a given experiment is replicated".}
#' \item{p_values_Q05}{Participants’ True/False/I don’t know response to: “Suppose that a research article reports p= .001 to support a research claim (alpha = .05). Please indicate whether the following statements are True or False: The probability that the results of the given study are replicable is not equal to 1-p”.}
#' \item{p_values_Q06}{Participants’ True/False/I don’t know response to: “Suppose that a research article reports p= .001 to support a research claim (alpha = .05). Please indicate whether the following statements are True or False: The value p = .001 does not directly confirm that the effect size was large”.}
#' \item{p_values_Q07}{Participants’ True/False/I don’t know response to: “Suppose that a research article reports p= .001 to support a research claim (alpha = .05). Please indicate whether the following statements are True or False: Obtaining a statistically significant result implies that the effect detected is important”.}
#' \item{p_values_Q08}{Participants’ True/False/I don’t know response to: “Suppose that a research article reports p= .001 to support a research claim (alpha = .05). Please indicate whether the following statements are True or False: The p-value of a statistical test is the probability of the observed result or a more extreme result, assuming the null hypothesis is true”.}
#' \item{confidence_intervals_Q01}{Participants’ True/False/I don’t know response to: “If two 95% confidence intervals around the means overlap, then the difference between the two estimates is necessarily non-significant (alpha = .05)”.}
#' \item{confidence_intervals_Q02}{Participants’ True/False/I don’t know response to: “An observed 95% confidence interval does not predict that 95% of the estimates from future studies will fall inside the observed interval.”.}
#' \item{statistics_concepts_Q01}{Participants’ response to “A researcher performs an experiment and calculates the sample mean and its 95% confidence interval (CI). Suppose that they repeated the experiment in exactly the same way, but with a new sample. What is the probability (0-100%) that they would find a sample mean in the second experiment that falls within the original's CI?”.}
#' \item{statistics_concepts_Q02}{Participants’ response to “ If the difference between means is 1.5 and the standard deviation is 2, what is the standardised mean difference?”.}
#' \item{literature_Q01}{Participants’ response to “According to surveys of the literature, what percentage of papers published in psychology journals report statistically significant results in support of the hypothesis?”.}
#' \item{literature_Q02}{Participants’ response to “What percentage of ‘Registered Reports’ report statistically significant results in support of the hypothesis?”.}
#' \item{literature_Q03}{Participants’ response to “What is the average statistical power (in %) for detecting a medium effect for research published in psychology journals? (A "medium" effect here is equivalent to a Cohen's d of .5, a correlation of .3, or a partial eta squared of .0588)”.}
#' \item{QRPs_Q01}{Participants’ response to “According to self-report surveys, what percentage of researchers in psychology report deciding to exclude data points after first checking the impact on statistical significance?”.}
#' \item{QRPs_Q02}{Participants’ response to “According to self-report surveys, what percentage of researchers in psychology report collecting more data after inspecting whether the results are statistically significant?”.}
#' \item{replication_rates_Q01}{Participants’ response to “What percentage of replication studies from The Reproducibility Project Psychology (RPP) obtained a statistically significant result in the same direction as the original study?”.}
#' \item{replication_rates_Q02}{Participants’ response to “What percentage of replication studies from experimental economics obtained a statistically significant result in the same direction as the original study?”.}
#' \item{replication_rates_Q03}{Participants’ response to “Consider the major replication projects that have been undertaken in the social and behavioural sciences*. What percentage of replication studies obtained an effect size lower than that seen in the original study?  *Reproducibility Project Psychology, Experimental Economics Replication Project, Many Labs 1, 2 and 3, Experimental Philosophy Replicability Project, Life Outcomes of Personality Replication Project (LOOPR), Social Sciences Replication Project (Nature and Science)”.}
#' \item{practice_claim_1_lower_bound}{Participants’ lower bound replicability estimate for the first practice claim: “When holding and writing on a heavier clipboard, people assessing job applicants rate them as 'better overall', and 'more seriously interested in the position'. Original Study: p-value = 0.049, standardised effect size (r) = 0.270, sample size (n) = 54. "In our first study, testing influences of weight on impression formation, we had 54 passersby evaluate a job candidate by reviewing resumes on either light (340.2 g) or heavy (2041.2 g) clipboards. Participants using heavy clipboards rated the candidate as better overall (Table 1) (F(1, 52) = 4.08, P = 0.049) and specifically as displaying more serious interest in the position (F(1, 52) = 4.40, P = 0.041)."  Citation: Ackerman, J. M., Nocera, C. C. & Bargh, J. A. Incidental haptic sensations influence social judgements and decisions. Science 328, 1712–1715 (2010). What is the probability that a direct replication of this study would find a statistically significant effect in the same direction as the original claim (0-100%)? 0 means that you think that a direct replication would never succeed, even by chance. 100 means that you think that a direct replication would never fail, even by chance.”.}
#' \item{practice_claim_1_best_estimate}{Participants’ best replicability estimate for the first practice claim: “When holding and writing on a heavier clipboard, people assessing job applicants rate them as 'better overall', and 'more seriously interested in the position'. Original Study: p-value = 0.049, standardised effect size (r) = 0.270, sample size (n) = 54. "In our first study, testing influences of weight on impression formation, we had 54 passersby evaluate a job candidate by reviewing resumes on either light (340.2 g) or heavy (2041.2 g) clipboards. Participants using heavy clipboards rated the candidate as better overall (Table 1) (F(1, 52) = 4.08, P = 0.049) and specifically as displaying more serious interest in the position (F(1, 52) = 4.40, P = 0.041)."  Citation: Ackerman, J. M., Nocera, C. C. & Bargh, J. A. Incidental haptic sensations influence social judgements and decisions. Science 328, 1712–1715 (2010). What is the probability that a direct replication of this study would find a statistically significant effect in the same direction as the original claim (0-100%)? 0 means that you think that a direct replication would never succeed, even by chance. 100 means that you think that a direct replication would never fail, even by chance.”.}
#' \item{practice_claim_1_upper_bound}{Participants’ upper bound replicability estimate for the first practice claim: “When holding and writing on a heavier clipboard, people assessing job applicants rate them as 'better overall', and 'more seriously interested in the position'. Original Study: p-value = 0.049, standardised effect size (r) = 0.270, sample size (n) = 54. "In our first study, testing influences of weight on impression formation, we had 54 passersby evaluate a job candidate by reviewing resumes on either light (340.2 g) or heavy (2041.2 g) clipboards. Participants using heavy clipboards rated the candidate as better overall (Table 1) (F(1, 52) = 4.08, P = 0.049) and specifically as displaying more serious interest in the position (F(1, 52) = 4.40, P = 0.041)."  Citation: Ackerman, J. M., Nocera, C. C. & Bargh, J. A. Incidental haptic sensations influence social judgements and decisions. Science 328, 1712–1715 (2010). What is the probability that a direct replication of this study would find a statistically significant effect in the same direction as the original claim (0-100%)? 0 means that you think that a direct replication would never succeed, even by chance. 100 means that you think that a direct replication would never fail, even by chance.”.}
#' \item{practice_claim_2_lower_bound}{Participants’ lower bound replicability estimate for the second practice claim: “Engaging in an outward-focused activity from a list (e.g. watching television or reading a book) for 12 minutes is rated as being more enjoyable than a 12 minute 'thinking period’ in which people just entertain themselves with their thoughts.  Original Study: p-value = 0.000044, standardised effect size (r) = 0.674, sample size (n) = 30.  "Would participants enjoy themselves more if they had something to do? In study 8, we randomly assigned 30 participants to entertain themselves with their own thoughts or to engage in external activities (such as reading a book, listening to music, or surfing the Web). We asked the latter participants not to communicate with others (e.g., via texting or emailing), so that we could compare nonsocial external activities (such as reading) with a nonsocial internal activity (thinking). As seen in Table 1, participants enjoyed the external activities much more than just thinking [t(28) = 4.83, P < 0.001], found it easier to concentrate [t(28) = 4.16, P < 0.001], and reported that their minds wandered less [t(28) = 3.61, P = 0.001]."  Citation: Wilson, T. D. et al. Just think: the challenges of the disengaged mind. Science 345, 75–77 (2014). What is the probability that a direct replication of this study would find a statistically significant effect in the same direction as the original claim (0-100%)?  0 means that you think that a direct replication would never succeed, even by chance. 100 means that you think that a direct replication would never fail, even by chance.”.}
#' \item{practice_claim_2_best_estimate}{Participants’ best replicability estimate for the second practice claim: “Engaging in an outward-focused activity from a list (e.g. watching television or reading a book) for 12 minutes is rated as being more enjoyable than a 12 minute 'thinking period’ in which people just entertain themselves with their thoughts.  Original Study: p-value = 0.000044, standardised effect size (r) = 0.674, sample size (n) = 30.  "Would participants enjoy themselves more if they had something to do? In study 8, we randomly assigned 30 participants to entertain themselves with their own thoughts or to engage in external activities (such as reading a book, listening to music, or surfing the Web). We asked the latter participants not to communicate with others (e.g., via texting or emailing), so that we could compare nonsocial external activities (such as reading) with a nonsocial internal activity (thinking). As seen in Table 1, participants enjoyed the external activities much more than just thinking [t(28) = 4.83, P < 0.001], found it easier to concentrate [t(28) = 4.16, P < 0.001], and reported that their minds wandered less [t(28) = 3.61, P = 0.001]."  Citation: Wilson, T. D. et al. Just think: the challenges of the disengaged mind. Science 345, 75–77 (2014). What is the probability that a direct replication of this study would find a statistically significant effect in the same direction as the original claim (0-100%)?  0 means that you think that a direct replication would never succeed, even by chance. 100 means that you think that a direct replication would never fail, even by chance.”}
#' \item{practice_claim_2_upper_bound}{Participants’ upper bound replicability estimate for the second practice claim: “Engaging in an outward-focused activity from a list (e.g. watching television or reading a book) for 12 minutes is rated as being more enjoyable than a 12 minute 'thinking period’ in which people just entertain themselves with their thoughts.  Original Study: p-value = 0.000044, standardised effect size (r) = 0.674, sample size (n) = 30.  "Would participants enjoy themselves more if they had something to do? In study 8, we randomly assigned 30 participants to entertain themselves with their own thoughts or to engage in external activities (such as reading a book, listening to music, or surfing the Web). We asked the latter participants not to communicate with others (e.g., via texting or emailing), so that we could compare nonsocial external activities (such as reading) with a nonsocial internal activity (thinking). As seen in Table 1, participants enjoyed the external activities much more than just thinking [t(28) = 4.83, P < 0.001], found it easier to concentrate [t(28) = 4.16, P < 0.001], and reported that their minds wandered less [t(28) = 3.61, P = 0.001]."  Citation: Wilson, T. D. et al. Just think: the challenges of the disengaged mind. Science 345, 75–77 (2014). What is the probability that a direct replication of this study would find a statistically significant effect in the same direction as the original claim (0-100%)?  0 means that you think that a direct replication would never succeed, even by chance. 100 means that you think that a direct replication would never fail, even by chance.”.}
#' \item{AOT_Q01}{Actively Open-Minded Thinking: Participants’ agree-disagree scale response to “Willingness to be convinced by opposing arguments is a sign of good character.”.}
#' \item{AOT_Q02}{Actively Open-Minded Thinking: Participants’ agree-disagree scale response to “People should take into consideration evidence that goes against conclusions they favour.”.}
#' \item{AOT_Q03}{Actively Open-Minded Thinking: Participants’ agree-disagree scale response to “Being undecided or unsure is the result of muddled thinking”.}
#' \item{AOT_Q04}{Actively Open-Minded Thinking: Participants’ agree-disagree scale response to “People should revise their conclusions in response to relevant new information”.}
#' \item{AOT_Q05}{Actively Open-Minded Thinking: Participants’ agree-disagree scale response to “Changing your mind is a sign of weakness”.}
#' \item{AOT_Q06}{Actively Open-Minded Thinking: Participants’ agree-disagree scale response to “People should search actively for reasons why they might be wrong”.}
#' \item{AOT_Q07}{Actively Open-Minded Thinking: Participants’ agree-disagree scale response to “It is OK to ignore evidence against your established beliefs.”.}
#' \item{AOT_Q08}{Actively Open-Minded Thinking: Participants’ agree-disagree scale response to “It is important to be loyal to your beliefs even when evidence is brought to bear against them”.}
#' \item{AOT_Q09}{Actively Open-Minded Thinking: Participants’ agree-disagree scale response to “There is nothing wrong with being undecided about many issues”.}
#' \item{AOT_Q10}{Actively Open-Minded Thinking: Participants’ agree-disagree scale response to “When faced with a puzzling question, we should try to consider more than one possible answer before reaching a conclusion”.}
#' \item{CRT_Q01}{Cognitive Reflection Test: Participants’ numeric estimate for “If it takes 2 nurses 2 minutes to measure the blood pressure of 2 patients, how long would it take 200 nurses to measure the blood pressure of 200 patients? (Please enter a number in minutes)”.}
#' \item{CRT_Q02}{Cognitive Reflection Test: Participants’ numeric estimate for “Soup and salad costs $5.50 in total. The soup costs a dollar more than the salad. How much does the salad cost? (Please enter a number in dollars, excluding the dollar sign)”.}
#' \item{CRT_Q03}{Cognitive Reflection Test: Participants’ numeric estimate for “Sally is making sun tea. Every hour, the concentration of the tea doubles. If it takes 6 hours for the tea to be ready, how long would it take for the tea to reach half of the final concentration? (Please enter a number in hours)”.}
#' \item{CRT_Q04}{Participants’ self-reported familiarity with the three previous CRT questions.}
#' \item{BN_Q01}{Berlin Numeracy: Participants’ response for “Out of 1,000 people in a small town 500 are members of a choir. Out of these 500 members in a choir 100 are men. Out of the 500 inhabitants that are not in a choir 300 are men. What is the probability that a randomly drawn man is a member of the choir? Please indicate the probability as percentage between 0 and 100 (%) ”.}
#' \item{BN_Q02}{Berlin Numeracy: Participants’ response for “Imagine we are throwing a loaded die (6 sides) 70 times. The probability that the die shows a 6 is twice as high as the probability of each of the other numbers. On average, out of these 70 throws how many times would the dice show the number 6?”.}
#' \item{BN_Q03}{Berlin Numeracy: Participants’ response for “Imagine we are throwing a five-sided die 50 times. On average, out of these 50 throws how many times would this five-sided die show an odd number (1, 3 or 5)?”.}
#' \item{BN_Q04}{Berlin Numeracy: Participants’ response for “In a forest 20% of mushrooms are red, 50% brown and 30% white. A red mushroom is poisonous with a probability of 20%. A mushroom that is not red is poisonous with a probability of 5%. What is the probability that a poisonous mushroom in the forest is red? Please indicate the probability as percentage between 0 and 100 (%)”.}
#' \item{quiz_literature}{Total correct answers for the “Literature” questions.}
#' \item{quiz_stats}{Total correct answers for the “Statistics (p-values, confidence intervals, statistical concepts)” questions.}
#' \item{quiz_QRP}{Total correct answers for the “QRP” questions.}
#' \item{quiz_replication}{Total correct answers for the “Replication Rates” and “Practice Claim” questions.}
#' }
#' @examples
#' demographics
"demographics"

#' @importFrom tibble tibble
NULL